name: 'password safe library action'
description: 'password safe library action'
inputs:
  client-id:
    description: 'client-id:'
    required: true
    default: ''
  client-secret:
    description: 'client-secret'
    required: true
    default: ''
  api-url:
    description: 'api-url'
    required: true
    default: ''
  verify-ca:
    description: 'verify-ca'
    required: false
    default: 'true'
  certificate:
    description: 'certificate'
    required: false
    default: ''
  certificate-key:
    description: 'certificate-key'
    required: false
    default: ''
  secret:
    description: 'secret'
    required: false
    default: ''
  secret-list:
    description: 'secret-list'
    required: false
    default: ''
  managed-account:
    description: 'managed-account'
    required: false
    default: ''
  managed-account-list:
    description: 'managed-account-list'
    required: false
    default: ''
outputs:
  output:
    description: 'output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.client-id }}
    - ${{ inputs.client-secret }}
    - ${{ inputs.api-url }}
    - ${{ inputs.verify-ca }}
    - ${{ inputs.certificate }}
    - ${{ inputs.certificate-key }}
    - ${{ inputs.secret }}
    - ${{ inputs.secret-list }}
    - ${{ inputs.managed-account }}
    - ${{ inputs.managed-account-list }}

