name: 'Secrets Safe Action'
author: 'BeyondTrust Corporation'
description: 'This custom action allows for the retrieval of ASCII secrets from an instance of Secrets Safe.'
inputs:
  client_id:
    description: 'The API OAuth Client ID is configured in BeyondInsight for your application. For use when authenticating to Secrets Safe'
    required: true
    default: ''
  client_secret:
    description: 'The API OAuth Client Secret is configured in BeyondInsight for your application. For use when authenticating to Secrets Safe.'
    required: true
    default: ''
  api_url:
    description: 'The API URL for the Secrets Safe instance from which to request a secret.'
    required: true
    default: ''
  verify_ca:
    description: 'Indicates whether to verify the certificate authority on the Secrets Safe instance. For use when authenticating to Secrets Safe.'
    required: false
    default: 'true'
  certificate:
    description: 'Content of the certificate (cert.pem) for use when authenticating with an API key using a Client Certificate.'
    required: false
    default: ''
  certificate_key:
    description: 'Certificate private key (key.pem). For use when authenticating with an API key using a Client Certificate.'
    required: false
    default: ''
  secret_path:
    description: 'Path to the Secrets Safe secret along with the value that the output secrets will be mapped to. For example, {"path": "folder1/folder2/title","output_id": "title"}'
    required: false
    default: ''
  managed_account_path:
    description: 'Path to the Managed Account secret along with the value that the output secrets will be mapped to. For example, {"path": "system/account","output_id": "account"}'
    required: false
    default: ''
  log_level:
    description: 'Log level'
    required: false
    default: 'INFO'
  path_separator:
    description: 'Secrets path and managed accounts path separator'
    required: false
    default: '/'
outputs:
  <output_id>:
    description: 'The action stores the retrieved secrets in output variables defined by the end user. The <output_id> must be a unique identifier within the outputs object. The <output_id> must start with a letter or _ and contain only alphanumeric characters, -, or _.'
runs:
  using: 'docker'
  image: 'docker://beyondtrust/secrets-github-action:1.0.0'
  args:
    - ${{ inputs.client_id }}
    - ${{ inputs.client_secret }}
    - ${{ inputs.api_url }}
    - ${{ inputs.verify_ca }}
    - ${{ inputs.certificate }}
    - ${{ inputs.certificate_key }}
    - ${{ inputs.secret_path }}
    - ${{ inputs.managed_account_path }}
    - ${{ inputs.log_level }}
    - ${{ inputs.path_separator }}
branding:
  icon: 'lock'
  color: 'orange'